[INSERT INTO co.t_ingredients (name) VALUES ('ginger beer');
, INSERT INTO co.t_ingredients (name) VALUES ('almond');
, INSERT INTO co.t_ingredients (name) VALUES ('champagne');
, INSERT INTO co.t_ingredients (name) VALUES ('mountain dew');
, INSERT INTO co.t_ingredients (name) VALUES ('lime juice');
, INSERT INTO co.t_ingredients (name) VALUES ('blueberry schnapps');
, INSERT INTO co.t_ingredients (name) VALUES ('apple juice');
, INSERT INTO co.t_ingredients (name) VALUES ('schweppes russchian');
, INSERT INTO co.t_ingredients (name) VALUES ('coffee');
, INSERT INTO co.t_ingredients (name) VALUES ('apple brandy');
, INSERT INTO co.t_ingredients (name) VALUES ('dry vermouth');
, INSERT INTO co.t_ingredients (name) VALUES ('apricot brandy');
, INSERT INTO co.t_ingredients (name) VALUES ('angelica root');
, INSERT INTO co.t_ingredients (name) VALUES ('allspice');
, INSERT INTO co.t_ingredients (name) VALUES ('lager');
, INSERT INTO co.t_ingredients (name) VALUES ('apricot');
, INSERT INTO co.t_ingredients (name) VALUES ('grand marnier');
, INSERT INTO co.t_ingredients (name) VALUES ('7-up');
, INSERT INTO co.t_ingredients (name) VALUES ('fruit');
, INSERT INTO co.t_ingredients (name) VALUES ('banana liqueur');
, INSERT INTO co.t_ingredients (name) VALUES ('candy');
, INSERT INTO co.t_ingredients (name) VALUES ('vodka');
, INSERT INTO co.t_ingredients (name) VALUES ('light rum');
, INSERT INTO co.t_ingredients (name) VALUES ('sweet vermouth');
, INSERT INTO co.t_ingredients (name) VALUES ('peach vodka');
, INSERT INTO co.t_ingredients (name) VALUES ('mint');
, INSERT INTO co.t_ingredients (name) VALUES ('vermouth');
, INSERT INTO co.t_ingredients (name) VALUES ('almond flavoring');
, INSERT INTO co.t_ingredients (name) VALUES ('orange');
, INSERT INTO co.t_ingredients (name) VALUES ('maraschino cherry');
, INSERT INTO co.t_ingredients (name) VALUES ('amaretto');
, INSERT INTO co.t_ingredients (name) VALUES ('apple cider');
, INSERT INTO co.t_ingredients (name) VALUES ('baileys irish cream');
, INSERT INTO co.t_ingredients (name) VALUES ('soda water');
, INSERT INTO co.t_ingredients (name) VALUES ('gin');
, INSERT INTO co.t_ingredients (name) VALUES ('malibu rum');
, INSERT INTO co.t_ingredients (name) VALUES ('milk');
, INSERT INTO co.t_ingredients (name) VALUES ('kahlua');
, INSERT INTO co.t_ingredients (name) VALUES ('pineapple juice');
, INSERT INTO co.t_ingredients (name) VALUES ('prosecco');
, INSERT INTO co.t_ingredients (name) VALUES ('cranberry juice');
, INSERT INTO co.t_ingredients (name) VALUES ('creme de cassis');
, INSERT INTO co.t_ingredients (name) VALUES ('brandy');
, INSERT INTO co.t_ingredients (name) VALUES ('wine');
, INSERT INTO co.t_ingredients (name) VALUES ('triple sec');
, INSERT INTO co.t_ingredients (name) VALUES ('nutmeg');
, INSERT INTO co.t_ingredients (name) VALUES ('peppermint schnapps');
, INSERT INTO co.t_ingredients (name) VALUES ('cointreau');
, INSERT INTO co.t_ingredients (name) VALUES ('lemon juice');
, INSERT INTO co.t_ingredients (name) VALUES ('cognac');
, INSERT INTO co.t_ingredients (name) VALUES ('water');
, INSERT INTO co.t_ingredients (name) VALUES ('green creme de menthe');
, INSERT INTO co.t_ingredients (name) VALUES ('coca-cola');
, INSERT INTO co.t_ingredients (name) VALUES ('heavy cream');
, INSERT INTO co.t_ingredients (name) VALUES ('food coloring');
, INSERT INTO co.t_ingredients (name) VALUES ('orange curacao');
, INSERT INTO co.t_ingredients (name) VALUES ('strawberry liqueur');
, INSERT INTO co.t_ingredients (name) VALUES ('coriander');
, INSERT INTO co.t_ingredients (name) VALUES ('grain alcohol');
, INSERT INTO co.t_ingredients (name) VALUES ('tequila');
, INSERT INTO co.t_ingredients (name) VALUES ('fresh lemon juice');
, INSERT INTO co.t_ingredients (name) VALUES ('wormwood');
, INSERT INTO co.t_ingredients (name) VALUES ('hpnotiq');
, INSERT INTO co.t_ingredients (name) VALUES ('creme de banane');
, INSERT INTO co.t_ingredients (name) VALUES ('orange peel');
, INSERT INTO co.t_ingredients (name) VALUES ('coconut rum');
, INSERT INTO co.t_ingredients (name) VALUES ('cherry');
, INSERT INTO co.t_ingredients (name) VALUES ('sugar syrup');
, INSERT INTO co.t_ingredients (name) VALUES ('grape soda');
, INSERT INTO co.t_ingredients (name) VALUES ('applejack');
, INSERT INTO co.t_ingredients (name) VALUES ('aperol');
, INSERT INTO co.t_ingredients (name) VALUES ('sour mix');
, INSERT INTO co.t_ingredients (name) VALUES ('johnnie walker');
, INSERT INTO co.t_ingredients (name) VALUES ('vanilla vodka');
, INSERT INTO co.t_ingredients (name) VALUES ('angostura bitters');
, INSERT INTO co.t_ingredients (name) VALUES ('sweet and sour');
, INSERT INTO co.t_ingredients (name) VALUES ('frangelico');
, INSERT INTO co.t_ingredients (name) VALUES ('wild turkey');
, INSERT INTO co.t_ingredients (name) VALUES ('cider');
, INSERT INTO co.t_ingredients (name) VALUES ('blackberry brandy');
, INSERT INTO co.t_ingredients (name) VALUES ('campari');
, INSERT INTO co.t_ingredients (name) VALUES ('lemon vodka');
, INSERT INTO co.t_ingredients (name) VALUES ('chambord raspberry liqueur');
, INSERT INTO co.t_ingredients (name) VALUES ('goldschlager');
, INSERT INTO co.t_ingredients (name) VALUES ('whipped cream');
, INSERT INTO co.t_ingredients (name) VALUES ('club soda');
, INSERT INTO co.t_ingredients (name) VALUES ('pisang ambon');
, INSERT INTO co.t_ingredients (name) VALUES ('egg white');
, INSERT INTO co.t_ingredients (name) VALUES ('roses sweetened lime juice');
, INSERT INTO co.t_ingredients (name) VALUES ('strawberries');
, INSERT INTO co.t_ingredients (name) VALUES ('fresh lime juice');
, INSERT INTO co.t_ingredients (name) VALUES ('absolut kurant');
, INSERT INTO co.t_ingredients (name) VALUES ('grapefruit juice');
, INSERT INTO co.t_ingredients (name) VALUES ('dark rum');
, INSERT INTO co.t_ingredients (name) VALUES ('lime');
, INSERT INTO co.t_ingredients (name) VALUES ('jack daniels');
, INSERT INTO co.t_ingredients (name) VALUES ('rum');
, INSERT INTO co.t_ingredients (name) VALUES ('midori melon liqueur');
, INSERT INTO co.t_ingredients (name) VALUES ('lemon');
, INSERT INTO co.t_ingredients (name) VALUES ('peach nectar');
, INSERT INTO co.t_ingredients (name) VALUES ('grenadine');
, INSERT INTO co.t_ingredients (name) VALUES ('white wine');
, INSERT INTO co.t_ingredients (name) VALUES ('tonic water');
, INSERT INTO co.t_ingredients (name) VALUES ('anise');
, INSERT INTO co.t_ingredients (name) VALUES ('fruit juice');
, INSERT INTO co.t_ingredients (name) VALUES ('cream');
, INSERT INTO co.t_ingredients (name) VALUES ('absolut vodka');
, INSERT INTO co.t_ingredients (name) VALUES ('marjoram leaves');
, INSERT INTO co.t_ingredients (name) VALUES ('añejo rum');
, INSERT INTO co.t_ingredients (name) VALUES ('dark creme de cacao');
, INSERT INTO co.t_ingredients (name) VALUES ('light cream');
, INSERT INTO co.t_ingredients (name) VALUES ('maui');
, INSERT INTO co.t_ingredients (name) VALUES ('cinnamon');
, INSERT INTO co.t_ingredients (name) VALUES ('jägermeister');
, INSERT INTO co.t_ingredients (name) VALUES ('blue curacao');
, INSERT INTO co.t_ingredients (name) VALUES ('ginger ale');
, INSERT INTO co.t_ingredients (name) VALUES ('sherry');
, INSERT INTO co.t_ingredients (name) VALUES ('kirschwasser');
, INSERT INTO co.t_ingredients (name) VALUES ('blended whiskey');
, INSERT INTO co.t_ingredients (name) VALUES ('absolut citron');
, INSERT INTO co.t_ingredients (name) VALUES ('sloe gin');
, INSERT INTO co.t_ingredients (name) VALUES ('rumple minze');
, INSERT INTO co.t_ingredients (name) VALUES ('tea');
, INSERT INTO co.t_ingredients (name) VALUES ('benedictine');
, INSERT INTO co.t_ingredients (name) VALUES ('lemon peel');
, INSERT INTO co.t_ingredients (name) VALUES ('chocolate ice-cream');
, INSERT INTO co.t_ingredients (name) VALUES ('yellow chartreuse');
, INSERT INTO co.t_ingredients (name) VALUES ('apple schnapps');
, INSERT INTO co.t_ingredients (name) VALUES ('151 proof rum');
, INSERT INTO co.t_ingredients (name) VALUES ('bitter lemon');
, INSERT INTO co.t_ingredients (name) VALUES ('creme de cacao');
, INSERT INTO co.t_ingredients (name) VALUES ('vanilla ice-cream');
, INSERT INTO co.t_ingredients (name) VALUES ('not specified');
, INSERT INTO co.t_ingredients (name) VALUES ('orange juice');
, INSERT INTO co.t_ingredients (name) VALUES ('ice');
, INSERT INTO co.t_ingredients (name) VALUES ('scotch');
, INSERT INTO co.t_ingredients (name) VALUES ('peach schnapps');
, INSERT INTO co.t_ingredients (name) VALUES ('southern comfort');
, INSERT INTO co.t_ingredients (name) VALUES ('coconut liqueur');
, INSERT INTO co.t_ingredients (name) VALUES ('lemonade');
, INSERT INTO co.t_ingredients (name) VALUES ('salt');
, INSERT INTO co.t_ingredients (name) VALUES ('kummel');
, INSERT INTO co.t_ingredients (name) VALUES ('jim beam');
, INSERT INTO co.t_ingredients (name) VALUES ('licorice root');
, INSERT INTO co.t_ingredients (name) VALUES ('glycerine');
, INSERT INTO co.t_ingredients (name) VALUES ('strawberry schnapps');
, INSERT INTO co.t_ingredients (name) VALUES ('hot chocolate');
, INSERT INTO co.t_ingredients (name) VALUES ('bourbon');
, INSERT INTO co.t_ingredients (name) VALUES ('orange bitters');
, INSERT INTO co.t_ingredients (name) VALUES ('bitters');
, INSERT INTO co.t_ingredients (name) VALUES ('white creme de menthe');
, INSERT INTO co.t_ingredients (name) VALUES ('sprite');
, INSERT INTO co.t_ingredients (name) VALUES ('sugar');
]